# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_DISABLE_GUI_ERRORS: 1
      DOTNET_GENERATE_ASPNET_CERTIFICATE: 0
      DOTNET_NOLOGO: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 10

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        include-prerelease: false

    - name: Restore
      run: dotnet restore -p:Configuration=Release

    - name: Build
      run: |
        $revisionId = $(git rev-parse --short $env:GITHUB_SHA)
        dotnet build -c Release --no-restore "-p:SourceRevisionId=$revisionId"

    - name: Test
      run: dotnet test -c Release --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput="$env:GITHUB_WORKSPACE/coverage/" -p:SkipAutoProps=true

    - uses: codecov/codecov-action@v3
      with:
        files: './coverage/coverage.cobertura.xml'
        flags: unittests
        fail_ci_if_error: true
        verbose: false
